export const seedDirections = [
  {
    slug: 'pediatrics',
    title: 'ПЕДИАТРИЯ',
    cardDescription: 'Приём детей от 0 до 18 лет. Осмотр, диагноз, лечение.',
    cardImageUrl: '/images/directions/pediatrics.svg',
    template: 'standard' as const,
    sortOrder: 1,
  },
  {
    slug: 'home-visit',
    title: 'ВЫЗОВ ВРАЧА НА ДОМ / ПАТРОНАЖ',
    cardDescription: 'Врач приедет домой. Патронаж новорождённого.',
    cardImageUrl: '/images/directions/home-visit.svg',
    template: 'steps' as const,
    sortOrder: 2,
  },
  {
    slug: 'certificates',
    title: 'СПРАВКИ',
    cardDescription: 'Лагерь, бассейн, секция, сад, школа — за один визит.',
    cardImageUrl: '/images/directions/certificates.svg',
    template: 'standard' as const,
    sortOrder: 3,
  },
  {
    slug: 'neurology',
    title: 'НЕВРОЛОГИЯ',
    cardDescription: 'СДВГ, задержка речи, тики, головные боли. Дети и взрослые.',
    cardImageUrl: '/images/directions/neurology.svg',
    template: 'standard' as const,
    sortOrder: 4,
  },
  {
    slug: 'epileptology',
    title: 'НЕВРОЛОГ-ЭПИЛЕПТОЛОГ',
    cardDescription: 'Судороги, эпилепсия, подбор терапии. Дети и взрослые.',
    cardImageUrl: '/images/directions/epileptology.svg',
    template: 'standard' as const,
    sortOrder: 5,
  },
  {
    slug: 'nutrition',
    title: 'НУТРИЦИОЛОГ',
    cardDescription: 'Питание, вес, прикорм. Индивидуальный подход к рациону. Дети и взрослые.',
    cardImageUrl: '/images/directions/nutrition.svg',
    template: 'standard' as const,
    sortOrder: 6,
  },
  {
    slug: 'gastroenterology',
    title: 'ГАСТРОЭНТЕРОЛОГ',
    cardDescription: 'Боли в животе, запоры, рефлюкс, ЖКТ. Дети и взрослые.',
    cardImageUrl: '/images/directions/gastroenterology.svg',
    template: 'standard' as const,
    sortOrder: 7,
  },
  {
    slug: 'pulmonology',
    title: 'ПУЛЬМОНОЛОГ',
    cardDescription: 'Кашель, астма, бронхиты. Спирометрия на приёме. Дети и взрослые.',
    cardImageUrl: '/images/directions/pulmonology.svg',
    template: 'standard' as const,
    sortOrder: 8,
  },
  {
    slug: 'endocrinology',
    title: 'ЭНДОКРИНОЛОГ',
    cardDescription: 'Рост, вес, щитовидная железа, сахар. Дети и взрослые.',
    cardImageUrl: '/images/directions/endocrinology.svg',
    template: 'standard' as const,
    sortOrder: 9,
  },
  {
    slug: 'psychiatry',
    title: 'ПСИХОТЕРАПИЯ',
    cardDescription: 'Тревожные расстройства, депрессия, нарушения поведения. Дети и взрослые.',
    cardImageUrl: '/images/directions/psychotherapy.svg',
    template: 'standard' as const,
    sortOrder: 10,
  },
  {
    slug: 'psychology',
    title: 'ПСИХОЛОГ',
    cardDescription: 'Поведение, страхи, школа, отношения. Дети и взрослые.',
    cardImageUrl: '/images/directions/psychology.svg',
    template: 'standard' as const,
    sortOrder: 11,
  },
];

export const seedPromotions = [
  {
    badge: 'Специальное предложение',
    title: 'Для второго ребенка из двойни',
    discount: '-30%',
    text: 'Заботимся о каждой семье! При одновременном лечении двоих детей из двойни, второй ребенок получает скидку 30% на все медицинские услуги.',
    tags: ['На все услуги', 'Без ограничений'],
    imageUrl: '/images/discounts/kids.png',
    accentColor: '#66d9b2',
    sortOrder: 1,
  },
  {
    badge: 'Социальная поддержка',
    title: 'Скидка для людей с инвалидностью',
    discount: '-30%',
    text: 'Поддерживаем особенные семьи. Предоставляем скидку 30% на медицинские услуги для детей и взрослых с подтвержденной инвалидностью.',
    tags: ['Требуется документ', 'На все услуги'],
    imageUrl: '/images/discounts/support.png',
    accentColor: '#c9a8e0',
    sortOrder: 2,
  },
  {
    badge: 'Налоговый вычет',
    title: 'Возврат налогового вычета за лечение',
    discount: '-13%',
    text: 'В случае прохождения лечения в нашей клинике, пациенты имеют право воспользоваться налоговым вычетом для частичного возмещения понесённых расходов.',
    tags: ['Возврат 13%'],
    imageUrl: '/images/discounts/tax.png',
    accentColor: '#ff9966',
    sortOrder: 3,
  },
];

export const seedDocuments = [
  {
    title: 'Лицензия на медицинскую деятельность',
    description: 'Разрешение на осуществление медицинской деятельности',
    fileUrl: '/images/docs/lic.pdf',
    originalFilename: 'Лицензия_клиники_Медведевой.pdf',
    sortOrder: 0,
  },
  {
    title: 'Свидетельство о регистрации',
    description: 'Документ о государственной регистрации юридического лица',
    fileUrl: '/images/docs/reg.webp',
    originalFilename: 'Свидетельство_о_регистрации.webp',
    sortOrder: 1,
  },
  {
    title: 'Прайс-лист',
    description: 'Актуальный перечень услуг и цен',
    fileUrl: '/images/docs/price.pdf',
    originalFilename: 'Прайс-лист_клиники_Медведевой.pdf',
    sortOrder: 2,
  },
  {
    title: 'Доверенность',
    description: null as string | null,
    fileUrl: '/images/docs/dover.pdf',
    originalFilename: 'Доверенность.pdf',
    sortOrder: 3,
  },
];
